"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { Minus, Plus, Search, ShoppingCart, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { completeSale, type PosActionResult } from "@/lib/actions/pos";
import { formatCurrencyIDR, roundMoney } from "@/lib/pos/currency";
import { PAYMENT_METHOD_LABELS } from "@/lib/pos/labels";

export type PosProduct = { id: string; name: string; sku: string; barcode: string | null; categoryId: string | null; sellingPrice: number; stock: number; unit: string };
export type PosCustomer = { id: string; name: string; phone: string | null; currentDebt: number; creditLimit: number | null };
type CartLine = PosProduct & { quantity: number; discountAmount: number };
type Settings = { taxEnabled: boolean; taxRate: number; serviceChargeEnabled: boolean; serviceChargeRate: number; allowNegativeStock: boolean };
const paymentMethods = ["CASH", "BANK_TRANSFER", "QRIS_MANUAL", "DEBIT", "CREDIT", "E_WALLET_MANUAL", "OTHER"];

export function PosWorkspace({ shift, products, categories, customers, settings }: { shift: { id: string; openedAt: string }; products: PosProduct[]; categories: { id: string; name: string }[]; customers: PosCustomer[]; settings: Settings }) {
  const [query, setQuery] = useState(""); const [categoryId, setCategoryId] = useState("all"); const [cart, setCart] = useState<CartLine[]>([]);
  const [customerId, setCustomerId] = useState("walk-in"); const [transactionDiscount, setTransactionDiscount] = useState(0); const [paymentMethod, setPaymentMethod] = useState("CASH"); const [cashReceived, setCashReceived] = useState(0); const [reference, setReference] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition(); const [completed, setCompleted] = useState<PosActionResult["sale"] | null>(null);
  const filteredProducts = useMemo(() => { const needle = query.trim().toLowerCase(); return products.filter((product) => (categoryId === "all" || product.categoryId === categoryId) && (!needle || product.name.toLowerCase().includes(needle) || product.sku.toLowerCase().includes(needle) || product.barcode?.toLowerCase().includes(needle))); }, [products, query, categoryId]);
  const subtotal = roundMoney(cart.reduce((sum, item) => sum + item.sellingPrice * item.quantity, 0));
  const itemDiscount = roundMoney(cart.reduce((sum, item) => sum + item.discountAmount, 0));
  const net = Math.max(0, subtotal - itemDiscount - transactionDiscount);
  const tax = settings.taxEnabled ? roundMoney(net * settings.taxRate / 100) : 0;
  const service = settings.serviceChargeEnabled ? roundMoney(net * settings.serviceChargeRate / 100) : 0;
  const total = roundMoney(net + tax + service);
  const change = paymentMethod === "CASH" ? Math.max(0, roundMoney(cashReceived - total)) : 0;

  function addProduct(product: PosProduct) { setError(null); setCart((current) => { const existing = current.find((line) => line.id === product.id); if (existing) { if (!settings.allowNegativeStock && existing.quantity + 1 > product.stock) { toast.error("Stok tidak cukup."); return current; } return current.map((line) => line.id === product.id ? { ...line, quantity: line.quantity + 1 } : line); } if (!settings.allowNegativeStock && product.stock <= 0) { toast.error("Produk kehabisan stok."); return current; } return [...current, { ...product, quantity: 1, discountAmount: 0 }]; }); }
  function updateQuantity(id: string, quantity: number) { const product = products.find((item) => item.id === id); if (!product) return; if (quantity <= 0) { setCart((current) => current.filter((item) => item.id !== id)); return; } if (!settings.allowNegativeStock && quantity > product.stock) { toast.error("Jumlah melebihi stok tersedia."); return; } setCart((current) => current.map((item) => item.id === id ? { ...item, quantity } : item)); }
  function updateItemDiscount(id: string, value: number) { setCart((current) => current.map((item) => item.id === id ? { ...item, discountAmount: Math.max(0, Math.min(value || 0, item.sellingPrice * item.quantity)) } : item)); }
  function submitSale() { setError(null); if (cart.length === 0) { setError("Keranjang masih kosong."); return; } if (total <= 0) { setError("Total transaksi harus lebih dari nol."); return; } if (paymentMethod === "CASH" && cashReceived < total) { setError("Uang tunai yang diterima masih kurang."); return; } const payload = { items: cart.map((item) => ({ productId: item.id, quantity: item.quantity, discountAmount: item.discountAmount })), customerId: customerId === "walk-in" ? null : customerId, transactionDiscount, paymentMethod, cashReceived, reference, notes }; const data = new FormData(); data.set("payload", JSON.stringify(payload)); startTransition(async () => { const result = await completeSale(data); if (result.success && result.sale) { setCompleted(result.sale); setCart([]); setTransactionDiscount(0); setCashReceived(0); setReference(""); setNotes(""); toast.success(`Transaksi ${result.sale.saleNumber} selesai.`); } else setError(result.error ?? "Transaksi gagal diproses."); }); }

  return <div className="space-y-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-xl font-semibold sm:text-2xl">Kasir (POS)</h1><p className="text-sm text-muted-foreground">Shift aktif sejak {new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short" }).format(new Date(shift.openedAt))}</p></div><Button variant="outline" render={<Link href={`/dashboard/shifts/${shift.id}`} />}>Lihat Shift</Button></div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(360px,0.75fr)]">
      <section className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama, SKU, atau barcode" className="pl-9" autoFocus /></div><Select value={categoryId} onValueChange={(value) => setCategoryId(value || "all")}><SelectTrigger aria-label="Filter kategori"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Semua kategori</SelectItem>{categories.map((category) => <SelectItem key={category.id} value={category.id}>{category.name}</SelectItem>)}</SelectContent></Select></div>
        {filteredProducts.length === 0 ? <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">Produk tidak ditemukan.</div> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filteredProducts.map((product) => <button key={product.id} type="button" onClick={() => addProduct(product)} className="rounded-lg border bg-card p-4 text-left transition-colors hover:border-primary hover:bg-primary/5 disabled:opacity-50" disabled={!settings.allowNegativeStock && product.stock <= 0}><div className="flex items-start justify-between gap-2"><p className="font-medium">{product.name}</p><span className="text-xs text-muted-foreground">{product.sku}</span></div><p className="mt-3 font-semibold text-primary">{formatCurrencyIDR(product.sellingPrice)}</p><p className={`mt-1 text-xs ${product.stock <= 0 ? "text-destructive" : "text-muted-foreground"}`}>Stok {product.stock} {product.unit}</p></button>)}</div>}
      </section>
      <aside className="space-y-4 rounded-xl border bg-card p-4 xl:sticky xl:top-20 xl:self-start"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><ShoppingCart className="size-4" aria-hidden="true" />Keranjang</h2><span className="text-sm text-muted-foreground">{cart.length} item</span></div>
        <div className="max-h-[38vh] space-y-3 overflow-y-auto pr-1">{cart.length === 0 ? <p className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">Pilih produk untuk memulai.</p> : cart.map((item) => <div key={item.id} className="space-y-2 rounded-lg border p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{formatCurrencyIDR(item.sellingPrice)} / {item.unit}</p></div><Button type="button" variant="ghost" size="icon-sm" aria-label={`Hapus ${item.name}`} onClick={() => updateQuantity(item.id, 0)}><Trash2 className="size-4" aria-hidden="true" /></Button></div><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-1"><Button type="button" variant="outline" size="icon-sm" aria-label={`Kurangi ${item.name}`} onClick={() => updateQuantity(item.id, item.quantity - 1)}><Minus className="size-3" aria-hidden="true" /></Button><Input type="number" min={0.001} step="1" value={item.quantity} onChange={(event) => updateQuantity(item.id, Number(event.target.value))} className="w-16 text-center" aria-label={`Jumlah ${item.name}`} /><Button type="button" variant="outline" size="icon-sm" aria-label={`Tambah ${item.name}`} onClick={() => updateQuantity(item.id, item.quantity + 1)}><Plus className="size-3" aria-hidden="true" /></Button></div><p className="text-sm font-medium">{formatCurrencyIDR(item.sellingPrice * item.quantity - item.discountAmount)}</p></div><div className="flex items-center gap-2"><Label htmlFor={`discount-${item.id}`} className="text-xs">Diskon item</Label><Input id={`discount-${item.id}`} type="number" min={0} max={item.sellingPrice * item.quantity} value={item.discountAmount} onChange={(event) => updateItemDiscount(item.id, Number(event.target.value))} className="h-7 flex-1" /></div></div>)}</div>
        <div className="space-y-3 border-t pt-4"><div className="space-y-2"><Label htmlFor="customer">Pelanggan</Label><Select value={customerId} onValueChange={(value) => setCustomerId(value || "walk-in")}><SelectTrigger id="customer" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="walk-in">Pelanggan umum</SelectItem>{customers.map((customer) => <SelectItem key={customer.id} value={customer.id}>{customer.name}{customer.phone ? ` · ${customer.phone}` : ""}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="transaction-discount">Diskon transaksi (Rp)</Label><Input id="transaction-discount" type="number" min={0} max={Math.max(0, subtotal - itemDiscount)} value={transactionDiscount} onChange={(event) => setTransactionDiscount(Math.max(0, Math.min(Number(event.target.value) || 0, subtotal - itemDiscount)))} /></div>
          <div className="space-y-1 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><span>{formatCurrencyIDR(subtotal)}</span></div>{itemDiscount > 0 ? <div className="flex justify-between"><span className="text-muted-foreground">Diskon item</span><span>-{formatCurrencyIDR(itemDiscount)}</span></div> : null}{transactionDiscount > 0 ? <div className="flex justify-between"><span className="text-muted-foreground">Diskon transaksi</span><span>-{formatCurrencyIDR(transactionDiscount)}</span></div> : null}{tax > 0 ? <div className="flex justify-between"><span className="text-muted-foreground">Pajak</span><span>{formatCurrencyIDR(tax)}</span></div> : null}{service > 0 ? <div className="flex justify-between"><span className="text-muted-foreground">Layanan</span><span>{formatCurrencyIDR(service)}</span></div> : null}<div className="flex justify-between border-t pt-2 text-base font-semibold"><span>Total</span><span>{formatCurrencyIDR(total)}</span></div></div>
          <div className="space-y-2"><Label htmlFor="payment-method">Metode pembayaran</Label><Select value={paymentMethod} onValueChange={(value) => setPaymentMethod(value || "CASH")}><SelectTrigger id="payment-method" className="w-full"><SelectValue /></SelectTrigger><SelectContent>{paymentMethods.map((method) => <SelectItem key={method} value={method}>{PAYMENT_METHOD_LABELS[method] ?? method}</SelectItem>)}</SelectContent></Select></div>{paymentMethod === "CASH" ? <div className="space-y-2"><Label htmlFor="cash-received">Uang diterima (Rp)</Label><Input id="cash-received" type="number" min={0} value={cashReceived} onChange={(event) => setCashReceived(Number(event.target.value) || 0)} /><div className="flex justify-between text-sm"><span className="text-muted-foreground">Kembalian</span><span className="font-medium">{formatCurrencyIDR(change)}</span></div></div> : <div className="space-y-2"><Label htmlFor="reference">Referensi (opsional)</Label><Input id="reference" value={reference} onChange={(event) => setReference(event.target.value)} maxLength={150} /></div>}<div className="space-y-2"><Label htmlFor="sale-notes">Catatan (opsional)</Label><Textarea id="sale-notes" value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={1000} /></div>{error ? <p role="alert" className="text-sm font-medium text-destructive">{error}</p> : null}<Button type="button" className="w-full" size="lg" disabled={pending || cart.length === 0} onClick={submitSale}>{pending ? "Memproses..." : `Bayar ${formatCurrencyIDR(total)}`}</Button>
        </div>
      </aside>
    </div>
    <Dialog open={Boolean(completed)} onOpenChange={(open) => { if (!open) setCompleted(null); }}><DialogContent><DialogHeader><DialogTitle>Transaksi Selesai</DialogTitle><DialogDescription>Stok, pembayaran, dan kas shift telah diperbarui.</DialogDescription></DialogHeader>{completed ? <div className="space-y-2 rounded-lg border p-4 text-sm"><div className="flex justify-between"><span>No. transaksi</span><strong>{completed.saleNumber}</strong></div><div className="flex justify-between"><span>No. struk</span><strong>{completed.receiptNumber}</strong></div><div className="flex justify-between"><span>Total</span><strong>{formatCurrencyIDR(completed.total)}</strong></div><div className="flex justify-between"><span>Kembalian</span><strong>{formatCurrencyIDR(completed.changeAmount)}</strong></div></div> : null}<DialogFooter><Button variant="outline" onClick={() => setCompleted(null)}>Transaksi Baru</Button>{completed ? <Button render={<Link href={`/dashboard/transactions/${completed.id}`} />}>Lihat Struk</Button> : null}</DialogFooter></DialogContent></Dialog>
  </div>;
}
