"use client";

import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useRef } from "react";
import { Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export function TransactionFilters({ cashiers, showCashier }: { cashiers: { id: string; name: string }[]; showCashier: boolean }) {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  function update(key: string, value: string) { const params = new URLSearchParams(searchParams.toString()); if (value) params.set(key, value); else params.delete(key); params.delete("page"); router.replace(`${pathname}?${params.toString()}`); }
  function search(value: string) { if (timeoutRef.current) clearTimeout(timeoutRef.current); timeoutRef.current = setTimeout(() => update("q", value), 350); }
  return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><div className="relative sm:col-span-2"><Search className="pointer-events-none absolute top-1/2 left-2.5 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><Input defaultValue={searchParams.get("q") ?? ""} onChange={(event) => search(event.target.value)} placeholder="No. transaksi atau pelanggan" className="pl-8" aria-label="Cari transaksi" /></div><Select defaultValue={searchParams.get("status") ?? "all"} onValueChange={(value) => update("status", value && value !== "all" ? value : "")}><SelectTrigger aria-label="Filter status transaksi"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Semua status</SelectItem><SelectItem value="COMPLETED">Selesai</SelectItem><SelectItem value="HELD">Ditahan</SelectItem><SelectItem value="VOIDED">Dibatalkan</SelectItem><SelectItem value="REFUNDED">Refund</SelectItem><SelectItem value="PARTIALLY_REFUNDED">Refund Sebagian</SelectItem></SelectContent></Select><Select defaultValue={searchParams.get("paymentStatus") ?? "all"} onValueChange={(value) => update("paymentStatus", value && value !== "all" ? value : "")}><SelectTrigger aria-label="Filter status pembayaran"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Semua pembayaran</SelectItem><SelectItem value="PAID">Lunas</SelectItem><SelectItem value="PARTIALLY_PAID">Sebagian</SelectItem><SelectItem value="UNPAID">Belum Bayar</SelectItem><SelectItem value="REFUNDED">Refund</SelectItem></SelectContent></Select>{showCashier ? <Select defaultValue={searchParams.get("cashierId") ?? "all"} onValueChange={(value) => update("cashierId", value && value !== "all" ? value : "")}><SelectTrigger aria-label="Filter operator"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Semua operator</SelectItem>{cashiers.map((cashier) => <SelectItem key={cashier.id} value={cashier.id}>{cashier.name}</SelectItem>)}</SelectContent></Select> : null}<Input type="date" defaultValue={searchParams.get("from") ?? ""} onChange={(event) => update("from", event.target.value)} aria-label="Tanggal mulai" /><Input type="date" defaultValue={searchParams.get("to") ?? ""} onChange={(event) => update("to", event.target.value)} aria-label="Tanggal akhir" /></div>;
}
