"use client";

import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useRef } from "react";
import { Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const STATUSES = ["DRAFT", "ORDERED", "PARTIALLY_RECEIVED", "RECEIVED", "CANCELLED"];
export function RestockFilters({ suppliers }: { suppliers: { id: string; name: string }[] }) { const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const timer = useRef<ReturnType<typeof setTimeout> | null>(null); function update(key: string, value: string) { const params = new URLSearchParams(searchParams.toString()); if (value) params.set(key, value); else params.delete(key); params.delete("page"); router.replace(`${pathname}?${params.toString()}`); } function search(value: string) { if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => update("q", value), 350); } return <div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1 sm:max-w-sm"><Search className="pointer-events-none absolute top-1/2 left-2.5 size-4 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><Input defaultValue={searchParams.get("q") ?? ""} onChange={(event) => search(event.target.value)} placeholder="No. pesanan atau supplier" className="pl-8" /></div><Select defaultValue={searchParams.get("status") ?? "all"} onValueChange={(value) => update("status", value && value !== "all" ? value : "")}><SelectTrigger aria-label="Filter status"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Semua status</SelectItem>{STATUSES.map((status) => <SelectItem key={status} value={status}>{status.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select><Select defaultValue={searchParams.get("supplierId") ?? "all"} onValueChange={(value) => update("supplierId", value && value !== "all" ? value : "")}><SelectTrigger aria-label="Filter supplier"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Semua supplier</SelectItem>{suppliers.map((supplier) => <SelectItem key={supplier.id} value={supplier.id}>{supplier.name}</SelectItem>)}</SelectContent></Select></div>; }
