"use client";

import { useState, useTransition } from "react";
import { Check, PackageCheck, Pencil, Trash2, XCircle } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { addRestockItem, cancelRestock, orderRestock, receiveRestock, removeRestockItem } from "@/lib/actions/restocks";

type Order = { id: string; orderNumber: string; status: string; items: { id: string; productName: string; unit: string; quantityOrdered: number; quantityReceived: number }[] };
type Product = { id: string; name: string; sku: string; unit: string; costPrice: number };

function EditItemsDialog({ order, products }: { order: Order; products: Product[] }) {
  const [open, setOpen] = useState(false); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  function add(data: FormData) { setError(null); startTransition(async () => { const result = await addRestockItem(order.id, { success: false }, data); if (result.success) toast.success("Item ditambahkan."); else setError(result.error ?? "Item gagal ditambahkan."); }); }
  function remove(itemId: string) { setError(null); startTransition(async () => { const result = await removeRestockItem(order.id, itemId); if (result.success) toast.success("Item dihapus."); else setError(result.error ?? "Item gagal dihapus."); }); }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button variant="outline"><Pencil className="size-4" aria-hidden="true" />Kelola Item</Button>} /><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>Item Restock</DialogTitle><DialogDescription>Item draf dapat ditambah atau dihapus sebelum pesanan dikirim.</DialogDescription></DialogHeader>{order.items.length > 0 ? <div className="space-y-2">{order.items.map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg border p-2 text-sm"><span>{item.productName} · {item.quantityOrdered} {item.unit}</span><Button type="button" variant="ghost" size="icon-sm" aria-label={`Hapus ${item.productName}`} disabled={pending} onClick={() => remove(item.id)}><Trash2 className="size-4" aria-hidden="true" /></Button></div>)}</div> : null}<form action={add} className="space-y-4 border-t pt-4"><div className="space-y-2"><Label htmlFor="restock-product">Produk</Label><Select name="productId"><SelectTrigger id="restock-product" className="w-full"><SelectValue placeholder="Pilih produk" /></SelectTrigger><SelectContent>{products.map((product) => <SelectItem key={product.id} value={product.id}>{product.name} · {product.sku}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="restock-quantity">Jumlah</Label><Input id="restock-quantity" name="quantityOrdered" type="number" min={0.001} step="0.001" required /></div><div className="space-y-2"><Label htmlFor="restock-cost">Biaya/unit</Label><Input id="restock-cost" name="unitCost" type="number" min={0} step="1" required /></div></div>{error ? <p role="alert" className="text-sm font-medium text-destructive">{error}</p> : null}<DialogFooter><Button type="submit" disabled={pending}>{pending ? "Menyimpan..." : "Tambah Item"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

function OrderButton({ order }: { order: Order }) { const [pending, startTransition] = useTransition(); function submit() { startTransition(async () => { const result = await orderRestock(order.id); if (result.success) toast.success("Pesanan ditandai dipesan."); else toast.error(result.error ?? "Status gagal diubah."); }); } return <Button type="button" onClick={submit} disabled={pending || order.items.length === 0}><Check className="size-4" aria-hidden="true" />{pending ? "Memproses..." : "Tandai Dipesan"}</Button>; }

function ReceiveDialog({ order }: { order: Order }) {
  const receivable = order.items.filter((item) => item.quantityReceived < item.quantityOrdered);
  const [open, setOpen] = useState(false); const [quantities, setQuantities] = useState<Record<string, number>>(() => Object.fromEntries(receivable.map((item) => [item.id, item.quantityOrdered - item.quantityReceived]))); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  function submit() { setError(null); const items = receivable.map((item) => ({ itemId: item.id, quantity: quantities[item.id] ?? 0 })).filter((item) => item.quantity > 0); startTransition(async () => { const result = await receiveRestock(order.id, JSON.stringify(items)); if (result.success) { toast.success("Penerimaan stok disimpan."); setOpen(false); } else setError(result.error ?? "Penerimaan gagal."); }); }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button><PackageCheck className="size-4" aria-hidden="true" />Terima Stok</Button>} /><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>Terima Stok</DialogTitle><DialogDescription>Masukkan jumlah yang tiba. Nilai awal adalah seluruh sisa pesanan; kurangi untuk penerimaan sebagian.</DialogDescription></DialogHeader><div className="space-y-3">{receivable.map((item) => <div key={item.id} className="grid items-end gap-3 sm:grid-cols-[1fr_130px]"><div><Label htmlFor={`receive-${item.id}`}>{item.productName}</Label><p className="text-xs text-muted-foreground">Sisa {item.quantityOrdered - item.quantityReceived} {item.unit}</p></div><Input id={`receive-${item.id}`} type="number" min={0} max={item.quantityOrdered - item.quantityReceived} step="0.001" value={quantities[item.id] ?? 0} onChange={(event) => setQuantities((current) => ({ ...current, [item.id]: Number(event.target.value) || 0 }))} /></div>)}</div>{error ? <p role="alert" className="text-sm font-medium text-destructive">{error}</p> : null}<DialogFooter><Button type="button" disabled={pending || receivable.length === 0} onClick={submit}>{pending ? "Memproses..." : "Simpan Penerimaan"}</Button></DialogFooter></DialogContent></Dialog>;
}

function CancelDialog({ order }: { order: Order }) { const [open, setOpen] = useState(false); const [reason, setReason] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition(); function submit() { setError(null); startTransition(async () => { const result = await cancelRestock(order.id, reason); if (result.success) { toast.success("Pesanan dibatalkan."); setOpen(false); } else setError(result.error ?? "Pesanan gagal dibatalkan."); }); } return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button variant="destructive"><XCircle className="size-4" aria-hidden="true" />Batalkan</Button>} /><DialogContent><DialogHeader><DialogTitle>Batalkan Restock</DialogTitle><DialogDescription>Stok yang sudah diterima tidak dibalik. Hanya sisa pesanan yang dibatalkan.</DialogDescription></DialogHeader><div className="space-y-2"><Label htmlFor={`cancel-${order.id}`}>Alasan</Label><Textarea id={`cancel-${order.id}`} value={reason} onChange={(event) => setReason(event.target.value)} minLength={3} maxLength={500} required /></div>{error ? <p role="alert" className="text-sm font-medium text-destructive">{error}</p> : null}<DialogFooter><Button type="button" variant="destructive" disabled={pending || reason.trim().length < 3} onClick={submit}>{pending ? "Membatalkan..." : "Konfirmasi"}</Button></DialogFooter></DialogContent></Dialog>; }

export function RestockOrderActions({ order, products }: { order: Order; products: Product[] }) { if (order.status === "RECEIVED" || order.status === "CANCELLED") return null; return <div className="flex flex-wrap gap-2">{order.status === "DRAFT" ? <><EditItemsDialog order={order} products={products} /><OrderButton order={order} /></> : <ReceiveDialog order={order} />}<CancelDialog order={order} /></div>; }
