"use client";

import { useTransition, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { updateStoreSettings } from "@/lib/actions/settings";

type Settings = { name: string; address: string | null; phone: string | null; email: string | null; receiptFooter: string | null; receiptWidth: string; taxEnabled: boolean; taxRate: number; serviceChargeEnabled: boolean; serviceChargeRate: number; allowNegativeStock: boolean; lowStockAlertEnabled: boolean };
export function SettingsForm({ settings }: { settings: Settings }) {
  const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  function submit(data: FormData) { setError(null); startTransition(async () => { const result = await updateStoreSettings({ success: false }, data); if (result.success) toast.success("Pengaturan toko disimpan."); else setError(result.error ?? "Pengaturan gagal disimpan."); }); }
  return <form action={submit} className="space-y-6"><section className="space-y-4 rounded-lg border bg-card p-6"><div><h2 className="font-semibold">Profil Toko</h2><p className="text-sm text-muted-foreground">Informasi ini ditampilkan pada struk.</p></div><div className="space-y-2"><Label htmlFor="store-name">Nama toko</Label><Input id="store-name" name="name" defaultValue={settings.name} required maxLength={150} /></div><div className="space-y-2"><Label htmlFor="store-address">Alamat</Label><Textarea id="store-address" name="address" defaultValue={settings.address ?? ""} maxLength={500} /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="store-phone">Telepon</Label><Input id="store-phone" name="phone" defaultValue={settings.phone ?? ""} maxLength={30} /></div><div className="space-y-2"><Label htmlFor="store-email">Email</Label><Input id="store-email" name="email" type="email" defaultValue={settings.email ?? ""} maxLength={150} /></div></div></section>
    <section className="space-y-4 rounded-lg border bg-card p-6"><div><h2 className="font-semibold">Struk</h2><p className="text-sm text-muted-foreground">Pilih lebar printer thermal dan pesan penutup.</p></div><div className="space-y-2"><Label htmlFor="receipt-width">Lebar struk</Label><Select name="receiptWidth" defaultValue={settings.receiptWidth}><SelectTrigger id="receipt-width" className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="58mm">58 mm</SelectItem><SelectItem value="80mm">80 mm</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label htmlFor="receipt-footer">Pesan penutup</Label><Textarea id="receipt-footer" name="receiptFooter" defaultValue={settings.receiptFooter ?? ""} maxLength={500} /></div></section>
    <section className="space-y-4 rounded-lg border bg-card p-6"><div><h2 className="font-semibold">Biaya Transaksi</h2><p className="text-sm text-muted-foreground">Persentase dihitung setelah diskon.</p></div><div className="grid gap-4 sm:grid-cols-2"><ToggleField name="taxEnabled" label="Aktifkan pajak" defaultChecked={settings.taxEnabled} /><div className="space-y-2"><Label htmlFor="tax-rate">Tarif pajak (%)</Label><Input id="tax-rate" name="taxRate" type="number" min={0} max={100} step="0.01" defaultValue={settings.taxRate} required /></div><ToggleField name="serviceChargeEnabled" label="Aktifkan biaya layanan" defaultChecked={settings.serviceChargeEnabled} /><div className="space-y-2"><Label htmlFor="service-rate">Biaya layanan (%)</Label><Input id="service-rate" name="serviceChargeRate" type="number" min={0} max={100} step="0.01" defaultValue={settings.serviceChargeRate} required /></div></div></section>
    <section className="space-y-4 rounded-lg border bg-card p-6"><div><h2 className="font-semibold">Aturan Stok</h2><p className="text-sm text-muted-foreground">Pengaturan diterapkan server-side saat transaksi.</p></div><ToggleField name="allowNegativeStock" label="Izinkan penjualan saat stok kurang" defaultChecked={settings.allowNegativeStock} /><ToggleField name="lowStockAlertEnabled" label="Aktifkan peringatan stok rendah" defaultChecked={settings.lowStockAlertEnabled} /></section>
    {error ? <p role="alert" className="text-sm font-medium text-destructive">{error}</p> : null}<Button type="submit" disabled={pending}>{pending ? "Menyimpan..." : "Simpan Pengaturan"}</Button>
  </form>;
}

function ToggleField({ name, label, defaultChecked }: { name: string; label: string; defaultChecked: boolean }) { return <label className="flex items-center justify-between gap-4 rounded-lg border p-3 text-sm font-medium"><span>{label}</span><input type="checkbox" name={name} defaultChecked={defaultChecked} className="size-4 accent-primary" /></label>; }
